TARGET_PATH=lib
TARGET=libccreactor.a
OBJ_DIR=obj

OBJ_FILE_PATH := $(shell find $(OBJ_DIR) -maxdepth 4 -type d)
OBJ_FILES_PATTERN = $(addsuffix /*.o, $(OBJ_FILE_PATH)) 
LIB_OBJ = $(wildcard $(OBJ_FILES_PATTERN)) 

.PHONY : all clean a 


all:
	ar -src $(TARGET_PATH)/$(TARGET)  $(LIB_OBJ) 
	ls -lh  $(TARGET_PATH)
	# md5sum $(TARGET_PATH)/$(TARGET)
clean:
	rm -rf lib/*
	rm -rf  obj/*

	
a:
	echo   $(LIB_OBJ)   $(OBJ_FILE_PATH)